language: node_js
node_js:
  - 9

branches:
  only:
    - master

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  provider: heroku

  api_key:
    secure: "ac5dcdb8-79a3-4611-a3e2-a54d160ab5c3"